// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9QkF1nkaeeMy2OyvXD-oviOb6paS2I2g',
    appId: '1:824139898687:web:c44a4a2f8e5468c0b0fd8a',
    messagingSenderId: '824139898687',
    projectId: 'flutter-chat-apk-4197c',
    authDomain: 'flutter-chat-apk-4197c.firebaseapp.com',
    storageBucket: 'flutter-chat-apk-4197c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC44gQskUTerT1octSSnNdjUs3js9dX1mI',
    appId: '1:824139898687:android:b3fa8371ed2fc999b0fd8a',
    messagingSenderId: '824139898687',
    projectId: 'flutter-chat-apk-4197c',
    storageBucket: 'flutter-chat-apk-4197c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1TA42l6Bxzw4x-RJ5YI9-kWoQNqCbGig',
    appId: '1:824139898687:ios:901ce59d84d2377fb0fd8a',
    messagingSenderId: '824139898687',
    projectId: 'flutter-chat-apk-4197c',
    storageBucket: 'flutter-chat-apk-4197c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1TA42l6Bxzw4x-RJ5YI9-kWoQNqCbGig',
    appId: '1:824139898687:ios:901ce59d84d2377fb0fd8a',
    messagingSenderId: '824139898687',
    projectId: 'flutter-chat-apk-4197c',
    storageBucket: 'flutter-chat-apk-4197c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9QkF1nkaeeMy2OyvXD-oviOb6paS2I2g',
    appId: '1:824139898687:web:ef2bc0b2741f7d9bb0fd8a',
    messagingSenderId: '824139898687',
    projectId: 'flutter-chat-apk-4197c',
    authDomain: 'flutter-chat-apk-4197c.firebaseapp.com',
    storageBucket: 'flutter-chat-apk-4197c.appspot.com',
  );
}
